name: exam_score_collection_tool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cunning_document_scanner: ^1.2.3
  flutter_image_compress: ^2.3.0
  photo_view: ^0.15.0
  saver_gallery: ^4.0.1
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  image_to_pdf_converter: ^0.0.1
  path_provider: ^2.1.5
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
