// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUMrV3B6DgRuvY9ptsX3niYBAvRz_Axl8',
    appId: '1:65396233679:android:34cc16f3371b7346536eba',
    messagingSenderId: '65396233679',
    projectId: 'class-todo-list',
    storageBucket: 'class-todo-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDid52FEyBw78TFwxAKZFxgkRPSpnbzZko',
    appId: '1:65396233679:ios:290d30d0fd21c584536eba',
    messagingSenderId: '65396233679',
    projectId: 'class-todo-list',
    storageBucket: 'class-todo-list.appspot.com',
    androidClientId: '65396233679-73rhj9jdq247svj1ptu4gjo1q44eev0j.apps.googleusercontent.com',
    iosClientId: '65396233679-bfnkeqrq9b55gqm38dsu3sms8gru9ghj.apps.googleusercontent.com',
    iosBundleId: 'com.ycy.examScoreCollectionTool',
  );
}
